/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import betterBlocks from "@qkix/strapi-plugin-better-blocks/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "better-blocks": betterBlocks,
    "strapi-cloud": strapiCloud,
    "users-permissions": usersPermissions,
  },
});
